cdcservice:
  build: ./new-cdc/eventuate-local-java-cdc-sql-service
  ports:
    - "8099:8080"
  links:
    - mysqlbinlogpipeline
    - postgrespollingpipeline
    - postgreswalpipeline
    - kafka
    - zookeeper
  environment:
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATE_CDC_READER_1_TYPE: mysql-binlog
    EVENTUATE_CDC_READER_1_DATASOURCEURL: jdbc:mysql://${DOCKER_HOST_IP}:3306/eventuate
    EVENTUATE_CDC_READER_1_DATASOURCEUSERNAME: mysqluser
    EVENTUATE_CDC_READER_1_DATASOURCEPASSWORD: mysqlpw
    EVENTUATE_CDC_READER_1_DATASOURCEDRIVERCLASSNAME: com.mysql.jdbc.Driver
    EVENTUATE_CDC_READER_1_LEADERSHIPLOCKPATH: /eventuatelocal/cdc/leader/pipeline/1
    EVENTUATE_CDC_READER_1_BINLOGCLIENTID: 1
    EVENTUATE_CDC_READER_1_CDCDBUSERNAME: root
    EVENTUATE_CDC_READER_1_CDCDBPASSWORD: rootpassword
    EVENTUATE_CDC_READER_1_READOLDDEBEZIUMDBOFFSETSTORAGETOPIC: "false"
    EVENTUATE_CDC_READER_1_MYSQLBINLOGCLIENTNAME: MySqlBinLog

    EVENTUATE_CDC_READER_2_TYPE: polling
    EVENTUATE_CDC_READER_2_DATASOURCEURL: jdbc:postgresql://${DOCKER_HOST_IP}/eventuate
    EVENTUATE_CDC_READER_2_DATASOURCEUSERNAME: eventuate
    EVENTUATE_CDC_READER_2_DATASOURCEPASSWORD: eventuate
    EVENTUATE_CDC_READER_2_DATASOURCEDRIVERCLASSNAME: org.postgresql.Driver
    EVENTUATE_CDC_READER_2_LEADERSHIPLOCKPATH: /eventuatelocal/cdc/leader/pipeline/2
    EVENTUATE_CDC_READER_2_BINLOGCLIENTID: 2

    EVENTUATE_CDC_READER_3_TYPE: postgres-wal
    EVENTUATE_CDC_READER_3_DATASOURCEURL: jdbc:postgresql://${DOCKER_HOST_IP}:5433/eventuate
    EVENTUATE_CDC_READER_3_DATASOURCEUSERNAME: eventuate
    EVENTUATE_CDC_READER_3_DATASOURCEPASSWORD: eventuate
    EVENTUATE_CDC_READER_3_DATASOURCEDRIVERCLASSNAME: org.postgresql.Driver
    EVENTUATE_CDC_READER_3_LEADERSHIPLOCKPATH: /eventuatelocal/cdc/leader/pipeline/3
    EVENTUATE_CDC_READER_3_BINLOGCLIENTID: 3


    EVENTUATE_CDC_PIPELINE_1_TYPE: eventuate-local
    EVENTUATE_CDC_PIPELINE_1_READER: 1

    EVENTUATE_CDC_PIPELINE_2_TYPE: eventuate-local
    EVENTUATE_CDC_PIPELINE_2_READER: 2

    EVENTUATE_CDC_PIPELINE_3_TYPE: eventuate-local
    EVENTUATE_CDC_PIPELINE_3_READER: 3
